baseURL = "https://newb.tokyo/"
languageCode = "ja-JP"
title = "newb.tokyo"
theme = "hugo-paper"
canonifyurls = true
publishDir = "docs"
staticDir = "static"
hasCJKLanguage = true
googleAnalytics = "UA-108444633-2"
relativeUrls = true

[params]
author = "umasoya"

# hugo-paper color style
color = "linen" # linen, wheat, gray, light

# SNS
twitter   = 'umasoya'
github    = 'umasoya'
instagram = 'umasoya0331'
facebook  = 'umasoya0331'
linkedin  = 'umasoya'

[[params.menu]]
name = "home"
path = "/"

[[params.menu]]
name = "about"
path = "/about/"
