version: '3.7'

services:

    node:
        image: node:lts-alpine
        init: true
        volumes:
            - .:/app:rw
            - node_modules:/app/node_modules:rw
        working_dir: /app
        ports:
          - 9000:9000

    hugo:
        build:
            context: ./docker/hugo
            dockerfile: Dockerfile
        volumes:
            - .:/umasoya.github.io:rw
        working_dir: /umasoya.github.io
        ports:
            - 1313:1313
            - 443:443
        command: hugo server --bind '0.0.0.0'
        logging:
            options:
                max-size: '100k'
                max-file: '3'

volumes:
    node_modules:
